import type { Metadata } from "next";
import { jua } from "@/public/fonts/fonts";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Funnection Personal Paper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jua.className}>{children}</body>
    </html>
  );
}
